apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_LOG_RETENTION_HOURS: "168"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
